import sys
import pickle

# Load the model
with open('model.pkl', 'rb') as f:
    model = pickle.load(f)

# Function to predict from symptoms
def predict_from_symptoms(symptoms):
    # Perform prediction using the loaded model
    prediction = model.predict([symptoms])
    return prediction

if __name__ == "__main__":
    
    symptoms_dict = {
        'abdominal cramp': 0,
        'abdominal distention': 1,
        'abnormal behavior': 2,
        'abnormal bleeding': 3,
        'abnormal sensation': 4,
        'abnormally frequent': 5,
        'abscess': 6,
        'aching': 7,
        'acne': 8,
        'acquiring drinking alcohol taking lot time': 9,
        'affected part turning white': 10,
        'anemia': 11,
        'anxiety': 12,
        'arm': 13,
        'attack pain': 14,
        'back': 15,
        'bacterial infection': 16,
        'bad breath': 17,
        'bad smelling thin vaginal discharge': 18,
        'bad smelling vaginal discharge': 19,
        'barky cough': 20,
        'belching': 21,
        'better sitting worse lying': 22,
        'birth baby younger week gestational age': 23,
        'bleeding gum': 24,
        'bleeding skin': 25,
        'blindness': 26,
        'blindness one eye': 27,
        'blister sunlight': 28,
        'bloating': 29,
        'blood stool': 30,
        'blood urine': 31,
        'bloody diarrhea': 32,
        'blue': 33,
        'bluish skin coloration': 34,
        'blurred vision': 35,
        'blurry vision': 36,
        'body tremor': 37,
        'bone pain': 38,
        'bowed leg': 39,
        'breakdown skeletal muscle': 40,
        'breathing problem': 41,
        'bruising': 42,
        'burning': 43,
        'burning redness eye': 44,
        'burning stabbing pain': 45,
        'burning urination': 46,
        'certain thought repeatedly': 47,
        'change bowel movement': 48,
        'change breast shape': 49,
        'change color': 50,
        'change hair': 51,
        'change reflex': 52,
        'change skin color red black': 53,
        'change sleeping eating pattern': 54,
        'change taste': 55,
        'change voice': 56,
        'characteristic facial feature': 57,
        'characteristic rash': 58,
        'chest discomfort': 59,
        'chest pain': 60,
        'chest tightness': 61,
        'chill': 62,
        'chronic cough': 63,
        'chronic pain bladder': 64,
        'clenched fist overlapping finger': 65,
        'close object appear blurry': 66,
        'clumsy': 67,
        'cm lump skin': 68,
        'cold sweat': 69,
        'coma': 70,
        'confused thinking': 71,
        'confusion': 72,
        'constipation': 73,
        'coolness': 74,
        'coordination': 75,
        'cough bloody mucus': 76,
        'cough sputum production': 77,
        'coughing': 78,
        'coughing blood': 79,
        'coughing including coughing blood': 80,
        'coughing mucus': 81,
        'crawl': 82,
        'cry episode': 83,
        'dark urine': 84,
        'darker': 85,
        'daytime sleepiness': 86,
        'death child le one year age': 87,
        'decreased ability feel pain': 88,
        'decreased ability see': 89,
        'decreased ability think': 90,
        'decreased ability think remember': 91,
        'decreased ability turn': 92,
        'decreased appetite': 93,
        'decreased motivation': 94,
        'decreased range motion': 95,
        'decreased taste': 96,
        'decreased vision': 97,
        'dehydration': 98,
        'delayed physical growth': 99,
        'delirium': 100,
        'delusion': 101,
        'dementia': 102,
        'depending subtype abdominal pain': 103,
        'depends organ involved': 104,
        'depressed mood': 105,
        'depression': 106,
        'dermatitis herpetiformis': 107,
        'developmental disability': 108,
        'diarrhea': 109,
        'diarrhea may bloody': 110,
        'diarrhea mixed blood': 111,
        'diarrhoea': 112,
        'difficulty breathing': 113,
        'difficulty cutting': 114,
        'difficulty eating': 115,
        'difficulty getting pregnant': 116,
        'difficulty remembering recent event': 117,
        'difficulty swallowing': 118,
        'difficulty walking': 119,
        'dimpling skin': 120,
        'discharge penis': 121,
        'disorientation': 122,
        'distant object appear blurry': 123,
        'distorted blurred vision distance': 124,
        'dizziness': 125,
        'double vision': 126,
        'drinking large amount alcohol long period': 127,
        'drooping eyelid': 128,
        'dry cough': 129,
        'dry damp skin': 130,
        'dry eye': 131,
        'dry mouth': 132,
        'ear pain': 133,
        'easy prolonged bleeding': 134,
        'emotional problem': 135,
        'enlarged lymph node neck': 136,
        'enlarged spleen': 137,
        'enlarged thyroid': 138,
        'enlargement thyroid': 139,
        'enlargement tonsil': 140,
        'episode severe': 141,
        'erythema marginatum': 142,
        'excess hair': 143,
        'excessive amount uterine bleeding': 144,
        'excessive daytime sleepiness': 145,
        'excessive salivation': 146,
        'expanding area redness site tick bite': 147,
        'extreme sadness': 148,
        'extremity weakness': 149,
        'eye pain': 150,
        'eye strain': 151,
        'eyestrain': 152,
        'fast heart rate': 153,
        'fast heartbeat': 154,
        'fatigue': 155,
        'fear water': 156,
        'feel need check thing repeatedly': 157,
        'feeling cold': 158,
        'feeling faint upon standing': 159,
        'feeling generally unwell': 160,
        'feeling like passing': 161,
        'feeling need urinate right away': 162,
        'feeling tired': 163,
        'feeling tired time': 164,
        'fever': 165,
        'firm': 166,
        'flat discolored spot bump may blister': 167,
        'flu like illness': 168,
        'flu like symptom': 169,
        'fluid filled blister scab': 170,
        'fluid nipple': 171,
        'frequent infection': 172,
        'frequent urination': 173,
        'fullness': 174,
        'gas': 175,
        'gradual loss coordination': 176,
        'growth delay': 177,
        'gum disease': 178,
        'hair loss': 179,
        'half ring finger': 180,
        'hallucination': 181,
        'hallucination usually hearing voice': 182,
        'hard swelling skin': 183,
        'hard time reading small print': 184,
        'headache': 185,
        'hearing loss': 186,
        'hearing sound external sound present': 187,
        'heartburn': 188,
        'heat intolerance': 189,
        'heavy period': 190,
        'high blood pressure': 191,
        'high body temperature': 192,
        'hoarse voice': 193,
        'hold reading material farther away': 194,
        'impaired communication': 195,
        'inability child': 196,
        'inability move facial muscle one side': 197,
        'inability move feel one side body': 198,
        'increased breath rate': 199,
        'increased breathing rate': 200,
        'increased fat': 201,
        'increased heart rate': 202,
        'increased hunger': 203,
        'increased risk broken bone': 204,
        'increased risk infection': 205,
        'increased thirst': 206,
        'increasing weakening': 207,
        'index': 208,
        'infertility': 209,
        'inflamed eye': 210,
        'insomnia': 211,
        'intellectual disability': 212,
        'involuntary muscle movement': 213,
        'involuntary sleep episode': 214,
        'irregular edge': 215,
        'irregular menstrual period': 216,
        'irregular menstruation': 217,
        'irritability': 218,
        'irritation': 219,
        'itchiness': 220,
        'itching': 221,
        'itching genital area': 222,
        'itching result trouble sleeping': 223,
        'itchy': 224,
        'itchy blister': 225,
        'itchy bump': 226,
        'itchy ear': 227,
        'jaundice': 228,
        'jaw': 229,
        'jerky body movement': 230,
        'joint bone pain': 231,
        'joint swelling': 232,
        'large amount watery diarrhea': 233,
        'large forehead': 234,
        'large lymph node': 235,
        'large lymph node around neck': 236,
        'leg swelling': 237,
        'light sensitivity': 238,
        'little pain': 239,
        'localized breast pain redness': 240,
        'long term fatigue': 241,
        'loose frequent bowel movement': 242,
        'loose teeth': 243,
        'loss appetite': 244,
        'loss consciousness may sweating': 245,
        'loss hair part head body': 246,
        'loss lot blood childbirth': 247,
        'loss smell': 248,
        'loss vision one side': 249,
        'low blood pressure': 250,
        'low energy': 251,
        'low red blood cell': 252,
        'lower abdominal pain': 253,
        'lump breast': 254,
        'lump bump neck': 255,
        'maculopapular rash': 256,
        'malabsorption': 257,
        'may symptom': 258,
        'memory problem': 259,
        'mental ability': 260,
        'mental change': 261,
        'mid dilated pupil': 262,
        'middle finger': 263,
        'mild moderate intellectual disability': 264,
        'minimal': 265,
        'missed period': 266,
        'mole increasing size': 267,
        'mood change': 268,
        'mood swing': 269,
        'mouth sore': 270,
        'mouth ulcer': 271,
        'multiple painful joint': 272,
        'muscle ache difficulty breathing': 273,
        'muscle cramp': 274,
        'muscle joint pain': 275,
        'muscle spasm': 276,
        'muscle weakness': 277,
        'muscle weakness beginning foot hand': 278,
        'muscle weakness resulting inability move': 279,
        'muscular pain': 280,
        'myalgia': 281,
        'nausea': 282,
        'nausea vomiting': 283,
        'nausea vomiting weight loss dehydration occur': 284,
        'nearly undetectable spell': 285,
        'nearsightedness': 286,
        'neck': 287,
        'neck stiffness': 288,
        'needing urinate often': 289,
        'newly inverted nipple': 290,
        'non itchy skin ulcer': 291,
        'non painful cyst middle eyelid': 292,
        'nonaligned eye': 293,
        'none non specific': 294,
        'numbness': 295,
        'object different size eye': 296,
        'one eye myopia eye hyperopia': 297,
        'opening upper lip may extend nose palate': 298,
        'others': 299,
        'overlying redness': 300,
        'pain along inside edge shinbone': 301,
        'pain area': 302,
        'pain around ear': 303,
        'pain doesnt go shingle': 304,
        'pain going leg lower back': 305,
        'pain sex': 306,
        'pain specific bone': 307,
        'painful': 308,
        'painful blister lower leg': 309,
        'painful heavy period': 310,
        'painful joint base big toe': 311,
        'painful rash occurring stripe': 312,
        'painful skin': 313,
        'painful swelling parotid gland': 314,
        'painful swollen joint': 315,
        'painful tender outer part elbow': 316,
        'painless': 317,
        'painless lump': 318,
        'pale color': 319,
        'pale skin': 320,
        'pallor': 321,
        'paralysis': 322,
        'patch thick': 323,
        'patch white skin': 324,
        'perform certain routine repeatedly': 325,
        'period vigorous shaking': 326,
        'persistent rough white red patch mouth lasting longer week': 327,
        'photophobia': 328,
        'physical disability': 329,
        'pimple like rash': 330,
        'pinkish': 331,
        'playing video game extremely long period time': 332,
        'poor ability tolerate cold': 333,
        'poor appetite': 334,
        'poor coordination': 335,
        'poor tolerance heat': 336,
        'post nasal drip': 337,
        'problem language': 338,
        'problem mood': 339,
        'problem understanding speaking': 340,
        'problem vision': 341,
        'profuse sweating': 342,
        'progressive muscle weakness': 343,
        'prolonged': 344,
        'prolonged cough': 345,
        'prominent': 346,
        'protein urine': 347,
        'psychosis': 348,
        'pulsing pain': 349,
        'purple colored skin affected area': 350,
        'purple colored skin lesion': 351,
        'raised': 352,
        'raised red blue lesion': 353,
        'random outburst laughter': 354,
        'rapid breathing': 355,
        'recurring episode wheezing': 356,
        'red': 357,
        'red eye': 358,
        'red purple darker skin': 359,
        'red rash': 360,
        'red scaly patch skin breast': 361,
        'red skin': 362,
        'red spot white eye': 363,
        'red without blister': 364,
        'reddish eye': 365,
        'redness': 366,
        'redness eye': 367,
        'repetitive behavior': 368,
        'restricted interest': 369,
        'right lower abdominal pain': 370,
        'rigidity': 371,
        'ringing ear heartbeat': 372,
        'rough skin growth': 373,
        'runny nose': 374,
        'scaly patch skin': 375,
        'scratchiness': 376,
        'seizure': 377,
        'sensitivity smell': 378,
        'sensitivity sound': 379,
        'severe intellectual disability': 380,
        'severe pain': 381,
        'severe pain lower back abdomen': 382,
        'shakiness': 383,
        'shaking': 384,
        'sharp chest pain': 385,
        'shivering': 386,
        'shock like pain one side face last second minute': 387,
        'short height': 388,
        'short stature': 389,
        'shortness breath': 390,
        'sit': 391,
        'skin blister': 392,
        'skin breakdown': 393,
        'skin lesion generally pink color project outward': 394,
        'skin peeling': 395,
        'sleep problem': 396,
        'sleeping problem': 397,
        'slowness movement': 398,
        'small': 399,
        'small blister break open form painful ulcer': 400,
        'small blister surrounding swelling': 401,
        'small face': 402,
        'small head': 403,
        'small jaw': 404,
        'sneezing': 405,
        'social withdrawal': 406,
        'sometimes symptom': 407,
        'sore arm leg': 408,
        'sore throat': 409,
        'sore wrist': 410,
        'stiff muscle': 411,
        'stiff neck': 412,
        'stiffness': 413,
        'stomach pain': 414,
        'stroke': 415,
        'stuffy itchy nose': 416,
        'stunted growth': 417,
        'sudden': 418,
        'sudden loss muscle strength': 419,
        'sweat': 420,
        'swell pain near tumor': 421,
        'swelling': 422,
        'swelling abdomen': 423,
        'swelling around eye': 424,
        'swelling hand foot': 425,
        'swollen': 426,
        'swollen hand foot': 427,
        'swollen lymph node': 428,
        'taste acid': 429,
        'temporary fleeting vision one eye': 430,
        'tender breast': 431,
        'testicular pain': 432,
        'tingling': 433,
        'tingling hand foot': 434,
        'tingling thumb': 435,
        'tiredness': 436,
        'tooth loss': 437,
        'tremor': 438,
        'triangular tissue growth cornea': 439,
        'trouble breathing nose': 440,
        'trouble coordination': 441,
        'trouble opening mouth': 442,
        'trouble seeing': 443,
        'trouble sensation': 444,
        'trouble sleeping': 445,
        'trouble social interaction': 446,
        'trouble speaking': 447,
        'trouble swallowing': 448,
        'trouble talking': 449,
        'trouble walking': 450,
        'typically none': 451,
        'ulcer': 452,
        'ulcer around genitals': 453,
        'ulceration': 454,
        'unable move': 455,
        'unexplained weight loss': 456,
        'unintended weight loss': 457,
        'unpleasant smell present breath': 458,
        'upper abdominal pain': 459,
        'usage resulting problem': 460,
        'vaginal bleeding': 461,
        'vaginal bleeding without pain': 462,
        'vaginal discharge': 463,
        'variable': 464,
        'vary depending part brain involved': 465,
        'varying degree muscle weakness': 466,
        'velvety skin': 467,
        'vision loss': 468,
        'vomiting': 469,
        'warm': 470,
        'wart': 471,
        'watery eye': 472,
        'weak grip': 473,
        'weak muscle': 474,
        'weakness limb': 475,
        'weakness numbness affected leg': 476,
        'webbed neck': 477,
        'weight gain': 478,
        'wet': 479,
        'wheezing': 480,
        'white patch vaginal discharge': 481,
        'widespread pain': 482,
        'withdrawal occurring stopping': 483,
        'worrying': 484,
        'yellow skin': 485,
        'yellowish coloration skin white eye': 486,
        'yellowish skin': 487,
        'yellowish skin crust': 488
 }


    disease_dict = {
        0: 'Abscess',
        1: 'Acquired Capillary Haemangioma of Eyelid',
        2: 'Acquired Immuno Deficiency Syndrome',
        3: 'Acute encephalitis syndrome',
        4: 'Adult Inclusion Conjunctivitis',
        5: 'Alcohol Abuse and Alcoholism',
        6: 'Alopecia (hair loss)',
        7: 'Alzheimer',
        8: 'Amaurosis Fugax',
        9: 'Amblyopia',
        10: 'Amoebiasis',
        11: 'Anaemia',
        12: 'Aniseikonia',
        13: 'Anisometropia',
        14: 'Antepartum hemorrhage (Bleeding in late pregnancy)',
        15: 'Anthrax',
        16: 'Anxiety',
        17: 'Appendicitis',
        18: 'Arthritis',
        19: 'Asbestos-related diseases',
        20: 'Aseptic meningitis',
        21: 'Asthma',
        22: 'Astigmatism',
        23: 'Atrophy',
        24: 'Autism',
        25: 'Bad Breath (Halitosis)',
        26: "Bell's Palsy",
        27: 'Beriberi',
        28: 'Black Death',
        29: 'Bleeding Gums',
        30: 'Blindness',
        31: 'Botulism',
        32: 'Brain Tumour',
        33: 'Breast Cancer / Carcinoma',
        34: 'Bronchitis',
        35: 'Brucellosis',
        36: 'Bubonic plague',
        37: 'Bunion',
        38: 'Burns',
        39: 'Calculi',
        40: 'Campylobacter infection',
        41: 'Cancer',
        42: 'Candidiasis',
        43: 'Carbon monoxide poisoning',
        44: 'Carpal Tunnel Syndrome',
        45: 'Cavities',
        46: 'Celiacs disease',
        47: 'Cerebral palsy',
        48: 'Chagas disease',
        49: 'Chalazion',
        50: 'Chickenpox',
        51: 'Chikungunya Fever',
        52: 'Childhood Exotropia',
        53: 'Chlamydia',
        54: 'Cholera',
        55: 'Chorea',
        56: 'Chronic fatigue syndrome',
        57: 'Chronic obstructive pulmonary disease (COPD)',
        58: 'Cleft Lip and Cleft Palate',
        59: 'Colitis',
        60: 'Colorectal Cancer',
        61: 'Common cold',
        62: 'Condyloma',
        63: 'Congenital anomalies (birth defects)',
        64: 'Congestive heart disease',
        65: 'Corneal Abrasion',
        66: 'Coronary Heart Disease',
        67: 'Coronavirus disease 2019 (COVID-19)',
        68: 'Cough',
        69: 'Crimean Congo haemorrhagic fever (CCHF)',
        70: 'Dehydration',
        71: 'Dementia',
        72: 'Dengue',
        73: 'Diabetes Mellitus',
        74: 'Diabetic Retinopathy',
        75: 'Diarrhea',
        76: 'Diphtheria',
        77: "Down's Syndrome",
        78: 'Dracunculiasis (guinea-worm disease)',
        79: 'Dysentery',
        80: 'Ear infection',
        81: 'Early pregnancy loss',
        82: 'Ebola',
        83: 'Eclampsia',
        84: 'Ectopic pregnancy',
        85: 'Eczema',
        86: 'Endometriosis',
        87: 'Epilepsy',
        88: 'Fibroids',
        89: 'Fibromyalgia',
        90: 'Food Poisoning',
        91: 'Frost Bite',
        92: 'GERD',
        93: 'Gaming disorder',
        94: 'Gangrene',
        95: 'Gastroenteritis',
        96: 'Genital herpes',
        97: 'Glaucoma',
        98: 'Goitre',
        99: 'Gonorrhea',
        100: 'Guillain-Barré syndrome',
        101: 'Haemophilia',
        102: 'Hand, Foot and Mouth Disease',
        103: 'Heat-Related Illnesses and Heat waves',
        104: 'Hepatitis',
        105: 'Hepatitis A',
        106: 'Hepatitis B',
        107: 'Hepatitis C',
        108: 'Hepatitis D',
        109: 'Hepatitis E',
        110: 'Herpes Simplex',
        111: 'High risk pregnancy',
        112: 'Human papillomavirus',
        113: 'Hypermetropia',
        114: 'Hyperthyroidism',
        115: 'Hypothyroid',
        116: 'Hypotonia',
        117: 'Impetigo',
        118: 'Inflammatory Bowel Disease',
        119: 'Influenza',
        120: 'Insomnia',
        121: 'Interstitial cystitis',
        122: 'Iritis',
        123: 'Iron Deficiency Anemia',
        124: 'Irritable bowel syndrome',
        125: 'Japanese Encephalitis',
        126: 'Jaundice',
        127: 'Kala-azar/ Leishmaniasis',
        128: 'Kaposi’s Sarcoma',
        129: 'Keratoconjunctivitis Sicca (Dry eye syndrome)',
        130: 'Keratoconus',
        131: 'Kuru',
        132: 'Laryngitis',
        133: 'Lead poisoning',
        134: 'Legionellosis',
        135: 'Leprosy',
        136: 'Leptospirosis',
        137: 'Leukemia',
        138: 'Lice',
        139: 'Lung cancer',
        140: 'Lupus erythematosus',
        141: 'Lyme disease',
        142: 'Lymphoma',
        143: 'Mad cow disease',
        144: 'Malaria',
        145: 'Marburg fever',
        146: 'Mastitis',
        147: 'Measles',
        148: 'Melanoma',
        149: 'Middle East respiratory syndrome coronavirus (MERS‐CoV)',
        150: 'Migraine',
        151: 'Mononucleosis',
        152: 'Mouth Breathing',
        153: 'Multiple myeloma',
        154: 'Multiple sclerosis',
        155: 'Mumps',
        156: 'Muscular dystrophy',
        157: 'Myasthenia gravis',
        158: 'Myelitis',
        159: 'Myocardial Infarction (Heart Attack)',
        160: 'Myopia',
        161: 'Narcolepsy',
        162: 'Nasal Polyps',
        163: 'Nausea and Vomiting of Pregnancy and  Hyperemesis gravidarum',
        164: 'Necrotizing Fasciitis',
        165: 'Neonatal Respiratory Disease Syndrome(NRDS)',
        166: 'Neoplasm',
        167: 'Neuralgia',
        168: 'Nipah virus infection',
        169: 'Obesity',
        170: 'Obsessive Compulsive Disorder',
        171: 'Oral Cancer',
        172: 'Orbital Dermoid',
        173: 'Osteoarthritis',
        174: 'Osteomyelitis',
        175: 'Osteoporosis',
        176: 'Paratyphoid fever',
        177: "Parkinson's Disease",
        178: 'Pelvic inflammatory disease',
        179: 'Perennial Allergic Conjunctivitis',
        180: 'Pericarditis',
        181: 'Peritonitis',
        182: 'Pinguecula',
        183: 'Pneumonia',
        184: 'Poliomyelitis',
        185: 'Polycystic ovary syndrome (PCOS)',
        186: 'Porphyria',
        187: 'Post Menopausal Bleeding',
        188: 'Post-herpetic neuralgia',
        189: 'Postpartum depression/ Perinatal depression',
        190: 'Preeclampsia',
        191: 'Premenstrual syndrome',
        192: 'Presbyopia',
        193: 'Preterm birth',
        194: 'Progeria',
        195: 'Psoriasis',
        196: 'Puerperal sepsis',
        197: 'Pulmonary embolism',
        198: 'Ques fever',
        199: 'Quinsy',
        200: 'Rabies',
        201: "Raynaud's Phenomenon",
        202: 'Repetitive strain injury',
        203: 'Rheumatic fever',
        204: 'Rheumatism',
        205: 'Rickets',
        206: 'Rift Valley fever',
        207: 'Rocky Mountain spotted fever',
        208: 'Rubella',
        209: 'SARS',
        210: 'SIDS',
        211: 'Sarcoidosis',
        212: 'Sarcoma',
        213: 'Scabies',
        214: 'Scarlet fever',
        215: 'Schizophrenia',
        216: 'Sciatica',
        217: 'Scrapie',
        218: 'Scrub Typhus',
        219: 'Scurvy',
        220: 'Sepsis',
        221: 'Sexually transmitted infections (STIs)',
        222: 'Shaken Baby Syndrome',
        223: 'Shigellosis',
        224: 'Shin splints',
        225: 'Shingles',
        226: 'Sickle-cell anemia',
        227: 'Smallpox',
        228: 'Stevens-Johnson syndrome',
        229: 'Stomach ulcers',
        230: 'Strep throat',
        231: 'Stroke',
        232: 'Sub-conjunctival Haemorrhage',
        233: 'Syphilis',
        234: 'Taeniasis',
        235: 'Taeniasis/cysticercosis',
        236: 'Tay-Sachs disease',
        237: 'Tennis elbow',
        238: 'Tetanus',
        239: 'Thalassaemia',
        240: 'Tinnitus',
        241: 'Tonsillitis',
        242: 'Toxic shock syndrome',
        243: 'Trachoma',
        244: 'Trichinosis',
        245: 'Trichomoniasis',
        246: 'Tuberculosis',
        247: 'Tularemia',
        248: 'Turners Syndrome',
        249: 'Urticaria',
        250: 'Varicose Veins',
        251: 'Vasovagal syncope',
        252: 'Vitamin B12 Deficiency',
        253: 'Vitiligo',
        254: 'Warkany syndrome',
        255: 'Warts',
        256: 'Yaws',
        257: 'Yellow Fever',
        258: 'Zika virus disease',
        259: 'lactose intolerance',
        260: 'papilloedema'
 }
    

    # symptoms = eyestrain,headache,distorted blurred vision distance

    # Get symptoms from command-line arguments
    symptoms = sys.argv[1]

    symptoms = symptoms.split(',')
    # print(symptoms)

    list_of_indices = []

    for symptom in symptoms:

        idx = symptoms_dict[symptom]
        list_of_indices.append(idx)

    symptom_list = [0 for _ in range(489)]

    for idx in list_of_indices:
        symptom_list[idx] = 1
    # Predict disease from symptoms
    dis_val = predict_from_symptoms(symptom_list)[0]


    # Print the prediction
    print(disease_dict[dis_val])
